<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SisDoc.Common\SisDoc.Common.csproj" />
    <ProjectReference Include="..\SisDoc.DataAccess\SisDoc.DataAccess.csproj" />
  </ItemGroup>

</Project>
