 services:
  sqlserver_minimalapiSisDoc:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_minimalapiSisDoc
    restart: always
    environment:
      MSSQL_SA_PASSWORD: "Password2026"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "express"
    ports:
      - 1501:1433
    volumes:
      - C:\Users\USUARIO\Documents\Docker\Volumenes\minimal_api:/var/opt/mssql/data